apiVersion: v1
kind: Service
metadata:
  name: kibana-es
  namespace: kube-logging
spec:
  selector:
    app: kibana
  type: NodePort
  ports:
    - port: 80
      targetPort: 5601
      nodePort: 30001
