apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-efs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aws-efs
  nfs:
    path: /
    server: <your-efs-id>.efs.<your-region>.amazonaws.com
    readOnly: false
