---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    kubernetes.io/createdby: aws-efs-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-efs
  name: efs
spec:
  storageClassName: aws-efs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
